# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test

    - name: Build application
      run: |
        echo "No build script specified"
      if: always()
      
    - name: Deploy to Staging
      if: success()
      env:
        DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
        DEPLOY_HOST: ${{ secrets.STAGING_HOST }}
        DEPLOY_USER: ${{ secrets.STAGING_USER }}
      run: |
        echo "Deploying to staging..."
        echo "$DEPLOY_KEY" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key
        ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST '
          cd ~;
          if [ ! -d "node-demo" ]; then
            git clone https://github.com/GideonIsBuilding/node-demo.git;
          else
            cd node-demo && git pull origin main;
          fi;
          sudo apt update && sudo apt install -y nodejs npm;
          cd ~/node-demo;
          npm install;
          node index.js;
        '

    - name: Deployment Status
      if: success()
      run: echo "Deployment to staging successful!"
